### PR TITLE
Fedora 23 compatibility

### PR DESCRIPTION
**Pull request by oleastre**
I tried to compile the current stable branch to fedora 23.

I got some problems (and solutions in this PR):
- static libraries should be compiled with the -fPIC flag
- scrolledwin test is not gtkmm3 compatible (was the cmake test erroneous ?)
- embedded lensfun installs it's library event if statically compiled.

Note that Fedora packaging tries to avoid bundled libraries. So, is there a way to use the shared version of lensfun, or is the bundled one a modified version that's required ?

### CODE REVIEW

**Comment by aferrero2707** [comment]
Hi! Thanks for the fixes, I've manually merged your pull request and committed the changes to the stable branch.

scrollwin.cc was a test that I forgot to remove from the standard compilation.

Concerning lensfun, the main motivation for bundling the code was that the lens correction module was constantly crashing under Ubuntu when using the photoflow executable from the PPA. I could not track the reason for the crash because it did not occur when manually compiling photoflow from sources. Hence I decided to at least temporarily bundle lensfun in order to be able to better track crashes if they occur again. As a bonus, the latest version is used for all distributions, instead of the older versions provided by some of them. If needed, I will make the use of the bundled version optional and controlled by a cmake flag.

I hope that everything will compile fine now.

**Comment by Joermungand** [comment]
Um, not exactly. Lensfun inclusion sort of spoils the day for Archlinux. 
While it compiles just fine, installing it triggers file conflicts with 
the lensfun package, which photoflow lists as dependency (which means 
there is no way of installing the package without making a mess of 
dependencies).

Now, the lensfun version in Arch is still 0.3.1, but I’m quite positive 
it will be upgraded soon. I’m in a bit of a puzzle with respect to the 
stable-branch PKGBUILD. On the one hand, I could change depends to 
lensfun-git, but that entails further issues, I’m not entirely sure 
about the scope of all these at the moment – all the more so as there 
are a host of other packages depending on lensfun. On the other, if 
there is no lensfun 0.3.2-specific code in PhotoFlow (which cannot work 
against 0.3.1), a cmake flag allowing for removing the lensfun bundle 
would save the day.

Thanx,

Alex

**Comment by aferrero2707** [comment]
@Alex: could this be due to the fact that, as Olivier pointed out, the bundled lensfun was installing the static library in the system directories, clearly conflicting with the system-wide lensfun installation? This should be solved by the latest commit to the stable branch...

Concerning the bundling, as I said it was a sort-of hack to get the lens correction tool work properly under Ubuntu (or at least better debug crashes if they will occur again). Could you maybe check if under Arch the lens correction tool was working fine in version 0.2.4? Then I have no problem making the bundling optional and flag-controlled (it will maybe take a couple of days).
By the way, there is nothing in photoflow that requires the latest lensfun version.

Thanks!

**Comment by Joermungand** [comment]
Yeah, it’s precisely that.

I’ve tested the lens correction tool (found under geom/Optical 
corrections, right?) with both 2.4 and the latest stable before the 
lensfun bundle. The former works just fine and correctly identifies my 
camera/lens models as stored in the raw file. The latter, however, 
starts a process that spits continuous (looping) x,y field/value pairs 
in the terminal, which does not stop even after exiting PhotoFlow. The 
glitch must be somewhere in between the two. I’ve kept all the 
intermediary compiled packages of the stable branch, so I can test each 
one in turn and tell you where things break, if it’s any help.

Nothing to thank me for. Just glad to help.

**Comment by aferrero2707** [comment]
The .messages in the latest are normal, they are there to debug the issue
on Ubuntu. I've removed them in the latest code.

I'll try to make the bundling optional this evening. Meanwhile, the latest
code should not install lens fun library anymore.

Thanks!
Il 01/dic/2015 22:47, "Joermungand" <notifications@github.com> ha scritto:

**Comment by Joermungand** [comment]
What I failed to mention was that the lens correction layer never 
managed to load. While the application behaved normally, it wouldn’t get 
to the point where the camera/lens got detected. I updated to the latest 
commit and everything works fine now. Thanks.

**Comment by aferrero2707** [comment]
Could we then decide to keep the bundled lensfun version on all distributions, at least until I manage to figure out why the system-wide lensfun crashes photoflow on Ubuntu?

**Comment by oleastre** [comment]
It's ok for me. 
I was just warning you, if you want to get Photoflow in the official fedora repositories, you should remove bundled libraries, or have a good reason to include them.
This does not apply for copr distributed builds as it is for now.

**Comment by Joermungand** [comment]
As long as it does not overwrite files owned by the lensfun package, 
Arch will be happy with it.

**Pull request closed without merging**
